//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int id_cliente { get; set; }
        public string nom_cliente { get; set; }
        public string a_paterno { get; set; }
        public string a_materno { get; set; }
        public string telefono { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int no_cuenta { get; set; }
    
        public virtual cuenta cuenta { get; set; }
    }
}
